### ISSUE TITLE
Segmentation error

### ISSUE THREAD

**Issue by alobo4** [src-d/seriate#11]
When I try `import seriate` within a conda env, I am getting the error below:

`Fatal Python error: Segmentation fault`

`Current thread 0x00007fec5a5a7740 (most recent call first):`
  `File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed`
  `File "<frozen importlib._bootstrap_external>", line 1043 in create_module`
  `File "<frozen importlib._bootstrap>", line 583 in module_from_spec`
  `File "<frozen importlib._bootstrap>", line 670 in _load_unlocked`
  `File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked`
  `File "<frozen importlib._bootstrap>", line 983 in _find_and_load`
  `File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed`
  `File "<frozen importlib._bootstrap>", line 1035 in _handle_fromlist`
  `File "/nas/longleaf/home/lobanov/anaconda3/envs/python7bucket/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 47 in <module>`
  `File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed`
  `File "<frozen importlib._bootstrap_external>", line 728 in exec_module`
  `File "<frozen importlib._bootstrap>", line 677 in _load_unlocked`
  `File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked`
  `File "<frozen importlib._bootstrap>", line 983 in _find_and_load`
  `File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed`
  `File "<frozen importlib._bootstrap>", line 1035 in _handle_fromlist`
  `File "/nas/longleaf/home/lobanov/anaconda3/envs/python7bucket/lib/python3.7/site-packages/ortools/constraint_solver/routing_enums_pb2.py", line 6 in <module>`
  `File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed`
  `File "<frozen importlib._bootstrap_external>", line 728 in exec_module`
  `File "<frozen importlib._bootstrap>", line 677 in _load_unlocked`
  `File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked`
  `File "<frozen importlib._bootstrap>", line 983 in _find_and_load`
  `File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed`
  `File "<frozen importlib._bootstrap>", line 1035 in _handle_fromlist`
  `File "/proj/dschridelab/ddray/seriate/seriate.py", line 6 in <module>`
  `File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed`
  `File "<frozen importlib._bootstrap_external>", line 728 in exec_module`
  `File "<frozen importlib._bootstrap>", line 677 in _load_unlocked`
  `File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked`
  `File "<frozen importlib._bootstrap>", line 983 in _find_and_load`
  `File "<stdin>", line 1 in <module>`
`Segmentation fault (core dumped)`

I meet all the requirements listed on the requirements.txt and was previously using the package about a week ago

**Comment by vmarkovtsev** [comment]
Hi! Conda is notoriously known to miscompile native extensions and is not supported. Unfortunately, I don't plan to add support for Conda. Sorry for closing without a solution.

I recommend using a regular pip install.
